-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg7vMeooqcZt6go+6k
qT+7U6TxJ2KiSEmRwR2fwosMgO6gCgYIKoZIzj0DAQehRANCAASgXKCasuutazBB
Z2lWI+4P8dVHo6POSKfFqjnpQ2N8lWDwMKm7gfn1h/raKh24NDUshXwYf33EIhzz
GDxQCf7t
-----END PRIVATE KEY-----